//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hydrostatic_Particulars_Table
    {
        public long Hydrostatic_Particulars_ID { get; set; }
        public long Ship_ID { get; set; }
        public Nullable<decimal> Mean_Draught_BP { get; set; }
        public Nullable<decimal> Trim_BP { get; set; }
        public Nullable<decimal> Displacement_Volume { get; set; }
        public Nullable<decimal> Displacement { get; set; }
        public Nullable<decimal> LCB { get; set; }
        public Nullable<decimal> TCB { get; set; }
        public Nullable<decimal> VCB { get; set; }
        public Nullable<decimal> LCB_Proportion_of_LBP_Perc { get; set; }
        public Nullable<decimal> LCF { get; set; }
        public Nullable<decimal> TCF { get; set; }
        public Nullable<decimal> VCF { get; set; }
        public Nullable<decimal> TPI { get; set; }
        public Nullable<decimal> Ixx { get; set; }
        public Nullable<decimal> Iyy { get; set; }
        public Nullable<decimal> Ixy { get; set; }
        public Nullable<decimal> Principal_Axes_Angle { get; set; }
        public Nullable<decimal> BMt { get; set; }
        public Nullable<decimal> BMl { get; set; }
        public Nullable<decimal> KMt { get; set; }
        public Nullable<decimal> KMl { get; set; }
        public Nullable<decimal> MCT_BP_CoB { get; set; }
        public Nullable<decimal> Section_Area_Amidships { get; set; }
        public Nullable<decimal> Section_Area_Maximum { get; set; }
        public Nullable<decimal> X_Section_Area_Maximum { get; set; }
        public Nullable<decimal> Waterplane_Area { get; set; }
        public Nullable<decimal> Wetted_Surface_Area { get; set; }
        public Nullable<decimal> CB { get; set; }
        public Nullable<decimal> CM { get; set; }
        public Nullable<decimal> CP { get; set; }
        public Nullable<decimal> CVP { get; set; }
        public Nullable<decimal> CWL { get; set; }
        public Nullable<decimal> Length_To_Displacement_Ratio { get; set; }
        public Nullable<decimal> Length_To_Breadth_Ratio { get; set; }
        public Nullable<decimal> Breadth_To_Draught_Ratio { get; set; }
        public Nullable<decimal> Emerged_Buoyancy { get; set; }
        public Nullable<decimal> Emerged_Buoyancy_Centroid_X { get; set; }
        public Nullable<decimal> Emerged_Buoyancy_Centroid_Y { get; set; }
        public Nullable<decimal> Emerged_Buoyancy_Centroid_Z { get; set; }
        public Nullable<decimal> Reserve_Of_Buoyancy { get; set; }
    
        public virtual Ship_Table Ship_Table { get; set; }
    }
}
