//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ship_Table()
        {
            this.Additional_Weight_Table = new HashSet<Additional_Weight_Table>();
            this.Ammunition_Components_Table = new HashSet<Ammunition_Components_Table>();
            this.Crew_And_Effects_Components_Table = new HashSet<Crew_And_Effects_Components_Table>();
            this.Hydrostatic_Particulars_Table = new HashSet<Hydrostatic_Particulars_Table>();
            this.Light_Ship_Weight_Table = new HashSet<Light_Ship_Weight_Table>();
            this.Provision_Store_Components_Table = new HashSet<Provision_Store_Components_Table>();
        }
    
        public long Ship_ID { get; set; }
        public string Ship_Name { get; set; }
        public string Ship_Description { get; set; }
        public Nullable<decimal> Length_Overall { get; set; }
        public Nullable<decimal> Length_of_Waterline { get; set; }
        public Nullable<decimal> Breadth_Overall { get; set; }
        public Nullable<decimal> Design_Draft { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Block_Coefficient { get; set; }
        public Nullable<decimal> Displacement { get; set; }
        public Nullable<byte> Standard_Loading_Condition_ID { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modification_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Additional_Weight_Table> Additional_Weight_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ammunition_Components_Table> Ammunition_Components_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crew_And_Effects_Components_Table> Crew_And_Effects_Components_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hydrostatic_Particulars_Table> Hydrostatic_Particulars_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Light_Ship_Weight_Table> Light_Ship_Weight_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provision_Store_Components_Table> Provision_Store_Components_Table { get; set; }
    }
}
