//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tank_Status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tank_Status()
        {
            this.Tank_Sounding_Table = new HashSet<Tank_Sounding_Table>();
        }
    
        public long Tank_Id { get; set; }
        public Nullable<long> Ship_ID { get; set; }
        public string Tank_Name { get; set; }
        public string Fluid_Type { get; set; }
        public Nullable<decimal> Fluid_Density__te_m3_ { get; set; }
        public string Fullness_definition { get; set; }
        public Nullable<decimal> Sounding__mm_ { get; set; }
        public Nullable<decimal> Weight___te_ { get; set; }
        public Nullable<decimal> LCG__mm_ { get; set; }
        public Nullable<decimal> TCG___mm_ { get; set; }
        public Nullable<decimal> VCG_Fluid__mm_ { get; set; }
        public Nullable<decimal> VCGT_Virtual__mm_ { get; set; }
        public Nullable<decimal> Transverse_FSM___te_m_ { get; set; }
        public Nullable<decimal> Longitudinal_FSM___te_m_ { get; set; }
        public Nullable<decimal> Weight_X_LCG { get; set; }
        public Nullable<decimal> Weight_X_TCG { get; set; }
        public Nullable<decimal> Weight_X_VCG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tank_Sounding_Table> Tank_Sounding_Table { get; set; }
    }
}
